name: SimpleGravityGun
version: '1.3'
main: fr.simplegravitygun.SimpleGravityGun
api-version: '1.19'
authors:
  - Axel
  - Mathildeuh

commands:
  gravitygun:
    description: Command for the gravity gun
    usage: /gravitygun <player>

