name: SimpleGravityGun
version: '${version}'
main: fr.simplegravitygun.SimpleGravityGun
api-version: '1.19'
commands:
  gravitygun:
    description: Command for the gravity gun
    usage: /gravitygun <player>

